name: maxtivity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.0+1
  auto_size_text: ^3.0.0
  equatable: ^2.0.7
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  sizer: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.2.3
  freezed: ^3.1.0
  json_serializable: ^6.9.5


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/
    - assets/animation/
    - assets/fonts/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf